// User models
export * from './user';

// Conversation models
export * from './conversation';

// Bot models
export * from './bot';

// Analytics models
export * from './analytics';

// Plugin models
export * from './plugin';

// Import schemas for migration system
import {
  USER_TABLE_SCHEMA,
  USER_PREFERENCES_TABLE_SCHEMA,
  USER_STATS_TABLE_SCHEMA,
  USER_SESSIONS_TABLE_SCHEMA,
  USER_ACTIVITY_TABLE_SCHEMA,
} from './user';

import {
  CONVERSATION_TABLE_SCHEMA,
  MESSAGE_TABLE_SCHEMA,
  CONVERSATION_CONTEXT_TABLE_SCHEMA,
  CONVERSATION_THREAD_TABLE_SCHEMA,
  CONVERSATION_PARTICIPANT_TABLE_SCHEMA,
} from './conversation';

import {
  BOT_CONFIG_TABLE_SCHEMA,
  BOT_CAPABILITY_TABLE_SCHEMA,
  BOT_MODIFICATION_TABLE_SCHEMA,
  BOT_STATE_TABLE_SCHEMA,
  BOT_PERFORMANCE_TABLE_SCHEMA,
} from './bot';

import {
  METRICS_TABLE_SCHEMA,
  EVENTS_TABLE_SCHEMA,
  PERFORMANCE_METRICS_TABLE_SCHEMA,
  USER_ANALYTICS_TABLE_SCHEMA,
  GUILD_ANALYTICS_TABLE_SCHEMA,
  SYSTEM_HEALTH_TABLE_SCHEMA,
  ANALYTICS_REPORTS_TABLE_SCHEMA,
} from './analytics';

import {
  PLUGIN_TABLE_SCHEMA,
  TOOL_TABLE_SCHEMA,
  PLUGIN_COMMAND_TABLE_SCHEMA,
  PLUGIN_EVENT_TABLE_SCHEMA,
  PLUGIN_DEPENDENCY_TABLE_SCHEMA,
  PLUGIN_PERMISSION_TABLE_SCHEMA,
  PLUGIN_CONFIG_TABLE_SCHEMA,
  PLUGIN_LOG_TABLE_SCHEMA,
  PLUGIN_METRICS_TABLE_SCHEMA,
} from './plugin';

// All schema definitions for migration system
export const ALL_TABLE_SCHEMAS = [
  // User tables
  USER_TABLE_SCHEMA,
  USER_PREFERENCES_TABLE_SCHEMA,
  USER_STATS_TABLE_SCHEMA,
  USER_SESSIONS_TABLE_SCHEMA,
  USER_ACTIVITY_TABLE_SCHEMA,
  
  // Conversation tables
  CONVERSATION_TABLE_SCHEMA,
  MESSAGE_TABLE_SCHEMA,
  CONVERSATION_CONTEXT_TABLE_SCHEMA,
  CONVERSATION_THREAD_TABLE_SCHEMA,
  CONVERSATION_PARTICIPANT_TABLE_SCHEMA,
  
  // Bot tables
  BOT_CONFIG_TABLE_SCHEMA,
  BOT_CAPABILITY_TABLE_SCHEMA,
  BOT_MODIFICATION_TABLE_SCHEMA,
  BOT_STATE_TABLE_SCHEMA,
  BOT_PERFORMANCE_TABLE_SCHEMA,
  
  // Analytics tables
  METRICS_TABLE_SCHEMA,
  EVENTS_TABLE_SCHEMA,
  PERFORMANCE_METRICS_TABLE_SCHEMA,
  USER_ANALYTICS_TABLE_SCHEMA,
  GUILD_ANALYTICS_TABLE_SCHEMA,
  SYSTEM_HEALTH_TABLE_SCHEMA,
  ANALYTICS_REPORTS_TABLE_SCHEMA,
  
  // Plugin tables
  PLUGIN_TABLE_SCHEMA,
  TOOL_TABLE_SCHEMA,
  PLUGIN_COMMAND_TABLE_SCHEMA,
  PLUGIN_EVENT_TABLE_SCHEMA,
  PLUGIN_DEPENDENCY_TABLE_SCHEMA,
  PLUGIN_PERMISSION_TABLE_SCHEMA,
  PLUGIN_CONFIG_TABLE_SCHEMA,
  PLUGIN_LOG_TABLE_SCHEMA,
  PLUGIN_METRICS_TABLE_SCHEMA,
];